language: ruby
rvm:
- 2.5
before_install:
  - rvm @global do gem uninstall bundler -a -x
  - rvm @global do gem install bundler -v 1.17.3
install:
- bundle install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: master
  on:
    branch: source
