title: Dr. Rick Wysocki
blurb: Assistant Teaching Professor - Ball State University. Queer archival rhetoric, new materialisms, and media theory.

paginate: 8
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate

scholar:
  source: ./_bibliography

collections:
  - current_projects
