title: Dr. Rick Wysocki
blurb: Assistant Teaching Professor - Ball State University. Queer archival rhetoric, new materialisms, and media theory.
email: rlwysockijr@gmail.com
twitter: http://twitter.com
linkedin: http://www.linkedin.com/in/rick-wysocki-08a94947/


paginate: 8
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-compose
  - jekyll-redirect-from
  - jekyll-scholar

scholar:
  source: ./_bibliography

collections:
  - current_projects

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile
